### ISSUE TITLE
Subscribe to Channels via Javascript Client

### ISSUE THREAD

**Issue by Koliham** [permitio/fastapi_websocket_pubsub#37] opened 2022-06-01 16:59 UTC
I want to build a Single Page Application that subscribes to channels.
The connection itself is accepted, but how do I subscribe to channels in Javascript?

**Comment by orweis** [comment] 2022-06-01 18:01
Hi, :)

This is actually a duplicate of this discussion:

https://github.com/permitio/fastapi_websocket_pubsub/discussions/7


Please check it out.

**Closed as completed** 2022-06-01 18:01 UTC
